apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines
data:
  indexing.yml:
    components:
      retriever:
        init_parameters:
          document_store:
            init_parameters:
              bm25_algorithm: BM25L
              bm25_parameters: {}
              bm25_tokenization_regex: (?u)\\b\\w\\w+\\b
              embedding_similarity_function: cosine
            type: haystack.document_stores.in_memory.document_store.InMemoryDocumentStore
          filters: null
          return_embedding: false
          scale_score: false
          top_k: 3
        type: haystack.components.retrievers.in_memory.embedding_retriever.InMemoryEmbeddingRetriever
      text_embedder:
        init_parameters:
          api_base_url: null
          api_key:
            env_vars:
              - OPENAI_API_KEY
            strict: true
            type: env_var
          dimensions: null
          model: text-embedding-ada-002
          organization: null
          prefix: ""
          suffix: ""
        type: haystack.components.embedders.openai_text_embedder.OpenAITextEmbedder
    connections:
      - receiver: retriever.query_embedding
        sender: text_embedder.embedding
    max_loops_allowed: 100
    metadata: {}
